/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividadewebservice;

import javax.swing.JOptionPane;

/**
 *
 * @author Thiago
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InpTemp = new javax.swing.JTextField();
        LTemp = new javax.swing.JLabel();
        BotaoTemp = new javax.swing.JButton();
        ResultadoTemp = new javax.swing.JLabel();
        InpValor1 = new javax.swing.JTextField();
        InpValor2 = new javax.swing.JTextField();
        LX = new javax.swing.JLabel();
        BotaoCompara = new javax.swing.JToggleButton();
        LCompara = new javax.swing.JLabel();
        ResultadoCompara = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InpTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InpTempActionPerformed(evt);
            }
        });

        LTemp.setText("Temperatura em ºF");

        BotaoTemp.setText("Converter");
        BotaoTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTempActionPerformed(evt);
            }
        });

        ResultadoTemp.setText("0");

        InpValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InpValor1ActionPerformed(evt);
            }
        });

        LX.setText("X");

        BotaoCompara.setText("Comparar");
        BotaoCompara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoComparaActionPerformed(evt);
            }
        });

        LCompara.setText("Compara qual o maior");

        ResultadoCompara.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(InpTemp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoTemp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotaoCompara)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ResultadoCompara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(InpValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LX)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InpValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LTemp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LCompara)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResultadoTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTemp)
                    .addComponent(LCompara))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InpTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoTemp))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InpValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LX)
                            .addComponent(InpValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoCompara)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResultadoTemp)
                    .addComponent(ResultadoCompara))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        LTemp.getAccessibleContext().setAccessibleName("Ltemperatura");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InpTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InpTempActionPerformed
        
    }//GEN-LAST:event_InpTempActionPerformed

    private void BotaoTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTempActionPerformed
        String inputText = InpTemp.getText(); 
        try {
            double tempFahrenheit = Double.parseDouble(inputText);
            
            double tempCelsius = fahrenheitParaCelsius(tempFahrenheit);
            ResultadoTemp.setText(tempCelsius + " °C");
        } catch (NumberFormatException ex) {
            // Trata a exceção caso o texto não seja um número válido
            JOptionPane.showMessageDialog(null, "Por favor, insira um número válido.");
        }
    }//GEN-LAST:event_BotaoTempActionPerformed

    private void BotaoComparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoComparaActionPerformed
        double valor1 = Double.parseDouble(InpValor1.getText());
        double valor2 = Double.parseDouble(InpValor2.getText());

        // Encontra o maior valor usando o método "maior"
        double maiorValor = maior(valor1, valor2);

        // Atualiza o texto da Label ResultadoCompara
        ResultadoCompara.setText("O maior valor é: " + maiorValor);
    }//GEN-LAST:event_BotaoComparaActionPerformed

    private void InpValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InpValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InpValor1ActionPerformed

    public static double fahrenheitParaCelsius(double fahrenheit) {
        return 5.0/9.0 * (fahrenheit - 32);
    }
    
    public static double maior(double a, double b) {
        return a > b ? a : b;
    }
    
    public static String tabuada(int numero) {
        StringBuilder resultado = new StringBuilder();
        resultado.append("Tabuada do número ").append(numero).append(":\n");

        for (int i = 1; i <= 10; i++) {
            resultado.append(numero).append(" x ").append(i).append(" = ").append(numero * i).append("\n");
        }

        return resultado.toString();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoCompara;
    private javax.swing.JButton BotaoTemp;
    private javax.swing.JTextField InpTemp;
    private javax.swing.JTextField InpValor1;
    private javax.swing.JTextField InpValor2;
    private javax.swing.JLabel LCompara;
    private javax.swing.JLabel LTemp;
    private javax.swing.JLabel LX;
    private javax.swing.JLabel ResultadoCompara;
    private javax.swing.JLabel ResultadoTemp;
    // End of variables declaration//GEN-END:variables
}
